### ISSUE TITLE
Criar banco

### ISSUE THREAD

**Issue by ambrosiaandrade** [ambrosiaandrade/proway-sistemaCompra#1]
TABELAS

Produto
Pedido
Itens do pedido (itens)
Cliente
podemos dividir as pessoas em física ou jurídica
Primeira ideia sobre as descrições
Produto

Produto (
id int not null auto_increment primary key,
descricao varchar(50) not null,
unidMedida float,
valorUnit double,
status boolean);

Pedido (
id int not null auto_increment primary key,
data Date,
idCliente int not null,
Endereço de entrega (CEP, Cidade, Bairro, Rua, Número)
situacao boolean,
valorTotal double,
QuantTotal double not null,
percenDesconto
);

**Comment by ambrosiaandrade** [comment]
Hi

**Comment by MaressaOliveira25** [comment]
Metas para a criação do Banco de dados..
Definir as características de cada banco de dados..
Analisar as tabelas para definir como ficarão divididas..

**Comment by MaressaOliveira25** [comment]
Iremos separar no banco as tabelas por tipo de pessoa ou iremos usar apenas uma tabela?

**Comment by MaressaOliveira25** [comment]
TABELAS
- Produto
- Pedido
- Itens do pedido (itens)
- Cliente
   * podemos dividir as pessoas em física ou jurídica 

Primeira ideia sobre as descrições
**Produto**

Produto (
       id int not null auto_increment primary key,
       descricao varchar(50) not null,
       unidMedida float,
       valorUnit double,
       status boolean);

Pedido (
       id int not null auto_increment primary key,
       data Date,
       idCliente int not null,
       Endereço de entrega (CEP, Cidade, Bairro, Rua, Número)
       situacao boolean,
       valorTotal double,
       QuantTotal double not null,
       percenDesconto
);
